language: generic
sudo: false
addons:
  apt:
    packages:
      - gnutls-bin
before_install:
  - source <(curl -fsSkL https://gist.githubusercontent.com/rejeep/ebcd57c3af83b049833b/raw)
  - evm install $EVM_EMACS --use --skip
  - cask install
env:
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26-pretest-travis
  - EVM_EMACS=emacs-git-snapshot-travis
script:
  - emacs --version
  - make test
